#!/bin/bash
	if [[ ${1:0:1} != "-" ]]; then exit; fi

	if [[ $1 == "-h" || $1 == "--help" || $1 == "-help" ]]; then
		echo 'Use cloud-bashrc to ensure you have valid X509 credentials. cloud-bashrc'
		echo 'performs the following:'
		echo
		echo 'o Checks to see if it is called from a login shell (first argument begins'
		echo '  with "-"). If not, the command will exit to avoid interfering with'
		echo '  remote shell commands (i.e. scp)'
		echo 'o Queries both the local (grid-proxy-info) and long-lived (myproxy-info)'
		echo '  proxy information to check for valid credentials.'
		echo 'o If either of the credentials has expired, or the local proxy has less'
		echo '  then 3 hours to live, or the long-lived proxy has less than 12 hours to'
		echo '  live, calls the appropriate command (either cloud-init or myproxy-logon)'
		echo '  to renew them.'
		echo 'o Formats and displays the remaining time for both credentials.'
		echo
		echo 'This command is intended to be used from your .bashrc as follows:'
		echo
		echo '  if [ -f /usr/local/bin/cloud-bashrc ]; then'
		echo '      /usr/local/bin/cloud-bashrc $0'
		echo '  fi'

		echo
		echo 'but can be executed from the command line with:'
		echo
		echo '  /usr/local/bin/cloud-logon'
		echo
		echo 'Specifying an argument of "-h" or "--help" or even "-help" will display'
		echo 'these messages".'
		exit
	fi

	gp_min_time_to_live=10800 # 3 hours
	mp_min_time_to_live=604800 # 168 hours

#	Re-initialize the MyProxy certificate if it has less than 12 hours to live.
	declare -i gp=`grid-proxy-info 2>/dev/null | awk '/timeleft/ {split($3, words, ":"); print (words[1]*3600)+(words[    2]*60)+words[3]}'`
	if (($gp > 0)); then
		declare -i mp=`myproxy-info 2>/dev/null | awk '/timeleft:/ {split($2, words, ":"); print (words[1]*3600)+(words[2]*60)+words[3]}'`
		if (($mp < $mp_min_time_to_live)); then
			set -e
			cloud-myproxy-init
		fi
	fi

#	Re-initialize the local certificate if it has less than 3 hours to live.
	if (($gp < $gp_min_time_to_live)); then 
		cloud-myproxy-logon
		
		declare -i mp=`myproxy-info 2>/dev/null | awk '/timeleft:/ {split($2, words, ":"); print (words[1]*3600)+(words[2]*60)+words[3]}'`
		if (($mp < $mp_min_time_to_live)); then
			set -e
			cloud-myproxy-init
		fi
	fi

	echo 
	echo "Time left for proxy certificates:"
	myproxy-info | awk '/timeleft/ {print sprintf("     myproxy cert = %10s %-12s", $2, $3 " " $4)}'
	grid-proxy-info | awk '/timeleft/ {print sprintf("       local cert = %10s %-12s\n",$3, " ")}'
