#!/bin/bash

set -e
EXPECTSCRIPT=`mktemp`

read -s -p "Enter new MyProxy pass phrase: " myproxypass
echo ""

export myproxypass

#get legacy proxy
echo "#!/usr/bin/expect
spawn myproxy-logon $@
expect \"Enter MyProxy pass phrase:\" { send \"\$env(myproxypass)\n\" }
expect eof
" > $EXPECTSCRIPT
chmod +x $EXPECTSCRIPT
$EXPECTSCRIPT | grep  "credential" 
rm $EXPECTSCRIPT

#get rfc proxy
rfcproxy=/tmp/x509up_u`id -u`.rfc
echo "#!/usr/bin/expect
spawn myproxy-logon $@ -k rfc -o $rfcproxy
expect \"Enter MyProxy pass phrase:\" { send \"\$env(myproxypass)\n\" }
expect eof
" > $EXPECTSCRIPT
chmod +x $EXPECTSCRIPT
$EXPECTSCRIPT | grep "credential"
rm $EXPECTSCRIPT

